spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: document-service
          uri: http://localhost:8091
          predicates:
            - Path=/document/**
#          filters:
#            - name: asdf
#              args:
#                headers: aa
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
#      jdbc-url: jdbc:h2:mem:common_db;INIT=RUNSCRIPT FROM 'classpath:h2init/schema.sql'\;RUNSCRIPT FROM 'classpath:h2init/data2.sql'
      jdbc-url: jdbc:h2:mem:common_db
      username: sa
      pool-name: common-cp


server:
  port: 8090
