spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8091
          predicates:
          - Path=/auth/**
        - id: document-service
          uri: http://localhost:8092
          predicates:
            - Path=/document/**
          filters:
            - RewritePath=/document/?(?<seg>.*), /$\{seg}
            - PreGatewayAuthorizationFilterFactory
#          filters:
#            - name: asdf
#              args:
#                headers: aa
server:
  port: 8090
